var weatherData = {
  currentConditions: {
    noReport: false,
    cityname: "",
    humidity: "",
    pressure: "",
    wind: "",
    windspeed: "",
    gusts: "",
    icon: "",
    cond: "",
    temp: "",
  },
  nearbyCities: {
    cities: [],
  },
  dayDesc: {
    noReport: false,
    cityname: "",
    times: [
      { timetitle: "", forecast: "" },
      { timetitle: "", forecast: "" },
      { timetitle: "", forecast: "" },
    ],
  },
  extendedForecast: {
    noReport: false,
    cityname: "",
    days: [
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
    ],
  },
  almanac: {
    noReport: false,
    today: "",
    tomorrow: "",
    sunrisetoday: "",
    sunrisetomorow: "",
    sunsettoday: "",
    sunsettomorrow: "",
    moonphases: [
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
    ],
  },
  alerts: { warnings: [] },
  radarUnavailable: false,
  extraLocal: {
    currentConditions: {
      noReport: false,
      cityname: "",
      humidity: "",
      pressure: "",
      wind: "",
      windspeed: "",
      gusts: "",
      icon: "",
      cond: "",
      temp: "",
    },
    dayDesc: {
      noReport: false,
      cityname: "",
      times: [
        { timetitle: "", forecast: "" },
        { timetitle: "", forecast: "" },
        { timetitle: "", forecast: "" },
      ],
    },
    extendedForecast: {
      noReport: false,
      cityname: "",
      days: [
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      ],
    },
  },
  airportConditions: {
    airports: [],
  },
  nationalAirports: {
    airports: [],
  },
  airportDelayList: [],
  spanish: {
    currentConditions: {
      noReport: false,
      cityname: "",
      humidity: "",
      pressure: "",
      wind: "",
      windspeed: "",
      gusts: "",
      icon: "",
      cond: "",
      temp: "",
    },
    nearbyCities: {
      cities: [],
    },
    extendedForecast: {
      noReport: false,
      cityname: "",
      days: [
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      ],
    },
    almanac: {
      noReport: false,
      today: "",
      tomorrow: "",
      sunrisetoday: "",
      sunrisetomorow: "",
      sunsettoday: "",
      sunsettomorrow: "",
      moonphases: [
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
      ],
    },
  },
  golf: {
    courseForecast: [
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
    ],
    resortForecast: [
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
    ],
  },
  uvIndex: {
    noReport: false,
    cityname: "",
    current: { uv: "", word: "" },
    forecast: [
      { day: "", time: "", uv: "", word: "" },
      { day: "", time: "", uv: "", word: "" },
      { day: "", time: "", uv: "", word: "" },
    ],
  },
};

for (var i = 0; i < locationConfig.golf.coursesAmount; i++) {
  grabCoursesData(i);
}

for (var i = 0; i < locationConfig.golf.resortsAmount; i++) {
  //grabResortsData(i)
}
