var weatherData = {
  currentConditions: {
    noReport: false,
    cityname: "",
    humidity: "",
    pressure: "",
    wind: "",
    windspeed: "",
    gusts: "",
    icon: "",
    cond: "",
    temp: "",
  },
  nearbyCities: {
    cities: [],
  },
  dayDesc: {
    noReport: false,
    cityname: "",
    times: [
      { timetitle: "", forecast: "" },
      { timetitle: "", forecast: "" },
      { timetitle: "", forecast: "" },
    ],
  },
  extendedForecast: {
    noReport: false,
    cityname: "",
    days: [
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
    ],
  },
  almanac: {
    noReport: false,
    today: "",
    tomorrow: "",
    sunrisetoday: "",
    sunrisetomorow: "",
    sunsettoday: "",
    sunsettomorrow: "",
    moonphases: [
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
      { moon: "blank", date: "" },
    ],
  },
  alerts: { warnings: [] },
  radarUnavailable: false,
  extraLocal: {
    currentConditions: {
      noReport: false,
      cityname: "",
      humidity: "",
      pressure: "",
      wind: "",
      windspeed: "",
      gusts: "",
      icon: "",
      cond: "",
      temp: "",
    },
    dayDesc: {
      noReport: false,
      cityname: "",
      times: [
        { timetitle: "", forecast: "" },
        { timetitle: "", forecast: "" },
        { timetitle: "", forecast: "" },
      ],
    },
    extendedForecast: {
      noReport: false,
      cityname: "",
      days: [
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      ],
    },
  },
  airportConditions: {
    airports: [],
  },
  nationalAirports: {
    airports: [
      {
        airportname: "Los Angeles Intl.",
        iataCode: "LAX",
        lat: "33.9422",
        lon: "-118.4036",
        temp: "",
        icon: "",
        windspeed: "",
        delay: "",
      },
      {
        airportname: "Denver Intl.",
        iataCode: "DEN",
        lat: "39.8494",
        lon: "-104.6729",
        temp: "",
        icon: "",
        windspeed: "",
        delay: "",
      },
      {
        airportname: "Dallas/Ft. Worth",
        iataCode: "DFW",
        lat: "32.8990",
        lon: "-97.0336",
        temp: "",
        icon: "",
        windspeed: "",
        delay: "",
      },
      {
        airportname: "Chicago/O'Hare",
        iataCode: "ORD",
        lat: "41.9803",
        lon: "-87.9090",
        temp: "",
        icon: "",
        windspeed: "",
        delay: "",
      },
      {
        airportname: "Atlanta Intl.",
        iataCode: "ATL",
        lat: "33.6324",
        lon: "-84.4333",
        temp: "",
        icon: "",
        windspeed: "",
        delay: "",
      },
      {
        airportname: "New York/JFK",
        iataCode: "JFK",
        lat: "40.6446",
        lon: "-73.7797",
        temp: "",
        icon: "",
        windspeed: "",
        delay: "",
      },
      {
        airportname: "San Francisco \nIntl.",
        iataCode: "SFO",
        lat: "37.6191",
        lon: "-122.3816",
        temp: "",
        icon: "",
        windspeed: "",
        delay: "",
      },
      {
        airportname: "Sea-Tac Intl.",
        iataCode: "SEA",
        lat: "47.4484",
        lon: "-122.3086",
        temp: "",
        icon: "",
        windspeed: "",
        delay: "",
      },
    ],
  },
  airportDelayList: [],
  spanish: {
    currentConditions: {
      noReport: false,
      cityname: "",
      humidity: "",
      pressure: "",
      wind: "",
      windspeed: "",
      gusts: "",
      icon: "",
      cond: "",
      temp: "",
    },
    nearbyCities: {
      cities: [],
    },
    extendedForecast: {
      noReport: false,
      cityname: "",
      days: [
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      ],
    },
    almanac: {
      noReport: false,
      today: "",
      tomorrow: "",
      sunrisetoday: "",
      sunrisetomorow: "",
      sunsettoday: "",
      sunsettomorrow: "",
      moonphases: [
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
      ],
    },
  },
  golf: {
    courseForecast: [
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
    ],
    resortForecast: [
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
    ],
  },
  uvIndex: {
    noReport: false,
    cityname: "",
    current: { uv: "", word: "" },
    forecast: [
      { day: "", time: "", uv: "", word: "" },
      { day: "", time: "", uv: "", word: "" },
      { day: "", time: "", uv: "", word: "" },
    ],
  },
};
