var weatherData = {
  currentConditions: {
    noReport: false,
    cityname: "",
    humidity: "",
    pressure: "",
    wind: "",
    windspeed: "",
    gusts: "",
    icon: "",
    cond: "",
    temp: "",
  },
  nearbyCities: {
    cities: [],
  },
  dayDesc: {
    noReport: false,
    cityname: "",
    times: [
      { timetitle: "", forecast: "" },
      { timetitle: "", forecast: "" },
      { timetitle: "", forecast: "" },
    ],
  },
  extendedForecast: {
    noReport: false,
    cityname: "",
    days: [
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
    ],
  },
  almanac: {
    time: {
      noReport: false,
      today: "",
      tomorrow: "",
      sunrisetoday: "",
      sunrisetomorow: "",
      sunsettoday: "",
      sunsettomorrow: "",
    },
    moonphases: {
      noReport: false,
      moons: [
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
        { moon: "blank", date: "" },
      ],
    },
  },
  alerts: { warnings: [] },
  radarUnavailable: false,
  extraLocal: {
    currentConditions: {
      noReport: false,
      cityname: "",
      humidity: "",
      pressure: "",
      wind: "",
      windspeed: "",
      gusts: "",
      icon: "",
      cond: "",
      temp: "",
    },
    dayDesc: {
      noReport: false,
      cityname: "",
      times: [
        { timetitle: "", forecast: "" },
        { timetitle: "", forecast: "" },
        { timetitle: "", forecast: "" },
      ],
    },
    extendedForecast: {
      noReport: false,
      cityname: "",
      days: [
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      ],
    },
  },
  airportConditions: {
    airports: [],
  },
  nationalAirports: {
    airports: [],
  },
  airportDelayList: [],
  spanish: {
    currentConditions: {
      noReport: false,
      cityname: "",
      humidity: "",
      pressure: "",
      wind: "",
      windspeed: "",
      gusts: "",
      icon: "",
      cond: "",
      temp: "",
    },
    nearbyCities: {
      cities: [],
    },
    extendedForecast: {
      noReport: false,
      cityname: "",
      days: [
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
        { dayname: "", icon: "", cond: "", high: "", low: "", windspeed: "" },
      ],
    },
    almanac: {
      time: {
        noReport: false,
        today: "",
        tomorrow: "",
        sunrisetoday: "",
        sunrisetomorow: "",
        sunsettoday: "",
        sunsettomorrow: "",
      },
      moonphases: {
        noReport: false,
        moons: [
          { moon: "blank", date: "" },
          { moon: "blank", date: "" },
          { moon: "blank", date: "" },
          { moon: "blank", date: "" },
          { moon: "blank", date: "" },
          { moon: "blank", date: "" },
          { moon: "blank", date: "" },
          { moon: "blank", date: "" },
        ],
      },
    },
  },
  golf: {
    courseForecast: [
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
    ],
    resortForecast: [
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
      {
        noReport: false,
        cityname: "",
        days: [
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
          {
            dayname: "",
            icon: "",
            cond: "",
            high: "",
            low: "",
            windspeed: "",
          },
        ],
      },
    ],
  },
  uvIndex: {
    current: { uv: "", word: "", noReport: false, cityname: "" },
    forecast: {
      noReport,
      days: [
        { day: "", time: "", uv: "", word: "" },
        { day: "", time: "", uv: "", word: "" },
        { day: "", time: "", uv: "", word: "" },
      ],
    },
  },
};

var providerConfig = null;

function grabData() {}
